// NiftyCore/Sources/Domain/Models/InviteToken.swift
// Piqd v0.6 — invite token value type. PRD §9 (FR-CIRCLE-03), SRS §6.3.4.
// Pure Swift — zero platform imports. Wire encode/decode + signature verification
// live in `InviteTokenCodec` (Task 3). This file is the in-memory shape only.

import Foundation

/// Payload exchanged at trusted-friend invitation time. Generated by the sender,
/// rendered into a QR or `piqd://invite/<token>` URL, decoded + verified by the
/// recipient before adding the sender to their local trusted circle.
///
/// `nonce` is a per-token random component so two invites generated by the same
/// sender don't share a wire payload (defense against trivial replay UX
/// confusion — actual replay rejection is handled at `accept()` by checking
/// against the existing friends list).
public struct InviteToken: Equatable, Sendable {
    public let senderID: UUID
    public let displayName: String
    public let publicKey: Data
    public let nonce: Data
    public let createdAt: Date

    public init(
        senderID: UUID,
        displayName: String,
        publicKey: Data,
        nonce: Data,
        createdAt: Date
    ) {
        self.senderID = senderID
        self.displayName = displayName
        self.publicKey = publicKey
        self.nonce = nonce
        self.createdAt = createdAt
    }
}
